INSERT INTO Awards(award_id, name) VALUES(1, 'Man Booker Prize');
INSERT INTO Awards(award_id, name) VALUES(2, 'Nobel Prize in Literature');
INSERT INTO Awards(award_id, name) VALUES(3, 'Pulitzer Prize');
INSERT INTO Awards(award_id, name) VALUES(4, 'John Newberry Medal');
INSERT INTO Awards(award_id, name) VALUES(5, 'Hugo Award for Best Novel');
INSERT INTO Awards(award_id, name) VALUES(6, 'National Book Award - Fiction');
INSERT INTO Awards(award_id, name) VALUES(7, 'National Book Award - Non-Fiction');
INSERT INTO Awards(award_id, name) VALUES(8, 'National Book Award - Poetry');
INSERT INTO Awards(award_id, name) VALUES(9, 'National Book Award - Young People''s Literature');
INSERT INTO Awards(award_id, name) VALUES(10, 'Bailey''s Women''s Prize for Fiction');
INSERT INTO Awards(award_id, name) VALUES(11, 'Academy Award for Best Picture');
INSERT INTO Awards(award_id, name) VALUES(12, 'Academy Award for Best Actor in a Leading Role');
INSERT INTO Awards(award_id, name) VALUES(13, 'Academy Award for Best Actress in a Leading Role');
INSERT INTO Awards(award_id, name) VALUES(14, 'Academy Award for Best Director');
INSERT INTO Awards(award_id, name) VALUES(15, 'Acadmey Award for Best Actor in a Supporting Role');
INSERT INTO Awards(award_id, name) VALUES(16, 'Academy Award for Best Actress in a Supporting Role');
INSERT INTO Awards(award_id, name) VALUES(17, 'Academy Award for Cinematography');
INSERT INTO Awards(award_id, name) VALUES(18, 'Academy Award for Costume Design');
INSERT INTO Awards(award_id, name) VALUES(19, 'Academy Award for Animated Feature Film');
INSERT INTO Awards(award_id, name) VALUES(20, 'Academy Award for Documentary');
