insert into Items (item_id, title, available, weekly_fine, damage_fine) values (1, 'Black Peter (Cerný Petr)', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (2, 'Your Highness', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (3, 'Blue Steel', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (4, 'Our Daily Bread (Unser täglich Brot)', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (5, 'Thirst (a.k.a. Three Strange Loves) (Törst)', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (6, 'Lewis Black: Stark Raving Black', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (7, 'Fat Girl (À ma soeur!)', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (8, 'Amateur', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (9, 'Shanghai Noon', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (10, 'Player''s Club, The', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (11, 'North Avenue Irregulars, The', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (12, 'Exorcism of Emily Rose, The', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (13, 'Legend of Lylah Clare, The', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (14, 'Hard Corps, The', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (15, 'Spaced Invaders', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (16, 'Last Picture Show, The', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (17, 'Picnic', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (18, 'Grand Isle', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (19, 'Women Aren''t Funny', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (20, 'Hotel Hell Vacation', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (21, 'People That Time Forgot, The', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (22, 'C''mon Man', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (23, 'Homem Que Desafiou o Diabo, O', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (24, 'J. Gang Meets Dynamite Harry, The (Jönssonligan & DynamitHarry)', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (25, 'Old Lady Who Walked in the Sea, The (Vieille qui marchait dans la mer, La)', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (26, 'Gangster No. 1', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (27, 'Float', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (28, 'Turtle Diary', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (29, 'Glory to the Filmmaker! (Kantoku · Banzai!)', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (30, 'Bang Bang Club, The', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (31, 'Man in the Iron Mask, The', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (32, 'Comic Book Villains', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (33, 'Martha Marcy May Marlene', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (34, 'Best Intentions, The (Den goda viljan)', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (35, 'Yes: 9012 Live', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (36, 'Hum Tumhare Hain Sanam', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (37, 'Not Safe for Work', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (38, 'Accidental Tourist, The', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (39, 'Company Business', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (40, 'Backtrack (Catchfire)', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (41, 'You and Me', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (42, 'Land Ho!', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (43, 'Dream a Little Dream', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (44, 'BookWars', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (45, 'Tabu: A Story of the South Seas', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (46, 'Asphalt Jungle, The', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (47, 'Rosemary''s Baby', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (48, 'Brassed Off', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (49, 'American Zombie', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (50, 'Warriors of Virtue', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (51, 'Quick Change', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (52, 'Good Boy!', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (53, 'New World (Shin-sae-gye)', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (54, 'A.K.A. Don Bonus', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (55, 'Tall Tale', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (56, 'Carlos', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (57, 'Dementia (a.k.a. Daughter of Horror)', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (58, 'Steppenwolf', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (59, 'Cinderfella', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (60, 'Rid of Me', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (61, 'Leaning Tower, The (Kalteva torni)', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (62, 'Mein Leben - Marcel Reich-Ranicki', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (63, 'Secret of Santa Vittoria, The', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (64, 'Godzilla vs. Gigan (Chikyû kogeki meirei: Gojira tai Gaigan)', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (65, 'Olympian Holiday (Loma) ', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (66, 'Long Way Round', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (67, 'City of the Living Dead (a.k.a. Gates of Hell, The) (Paura nella città dei morti viventi)', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (68, 'Illustrious Corpses (Cadaveri eccellenti)', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (69, 'Attack of the 50ft Cheerleader', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (70, 'Executive Suite', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (71, 'Daylight', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (72, 'Att stjäla en tjuv', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (73, 'Hardcover', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (74, 'Musikanten', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (75, 'Kid Cannabis', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (76, 'Final Fantasy: The Spirits Within', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (77, 'Enola Gay and the Atomic Bombing of Japan', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (78, 'Jackpot 2', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (79, 'Wishmaster 2: Evil Never Dies', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (80, 'Forgotten', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (81, 'American Crude', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (82, 'Bread, My Sweet, The (a.k.a. Wedding for Bella, A)', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (83, 'Violets Are Blue...', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (84, 'Out of the Furnace (Dust to Dust) (Low Dweller, The)', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (85, 'Ewok Adventure, The (a.k.a. Caravan of Courage: An Ewok Adventure)', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (86, 'The Brass Legend', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (87, 'Beloved (Les bien-aimées)', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (88, 'The Reverse', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (89, 'Mummy, The', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (90, 'Thelma & Louise', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (91, 'Compulsion', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (92, 'Divine Trash', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (93, 'Intermission', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (94, 'Nömadak TX', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (95, 'Lessons of Darkness (Lektionen in Finsternis)', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (96, 'Captains Courageous', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (97, 'First Squad: The Moment of Truth', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (98, 'King and the Mockingbird, The (Le roi et l''oiseau)', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (99, 'Little Girl (La pivellina)', 1, 5, 10);
insert into Items (item_id, title, available, weekly_fine, damage_fine) values (100, 'My Architect: A Son''s Journey', 1, 5, 10);
